version: '3'

services:
  php-fpm:
    build:
      dockerfile: Dockerfile.php-fpm
    container_name: php-fpm
    volumes:
      - ./laravel:/app
    working_dir: /app
    depends_on:
      - queue

  artisan:
    build:
      dockerfile: Dockerfile.php-fpm
    container_name: artisan
    volumes:
      - ./laravel:/app
    command: ["php", "artisan", "migrate"]
    depends_on:
      - composer

  nginx:
    build:
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./laravel:/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  queue:
    build:
      dockerfile: Dockerfile.queue
    container_name: queue
    volumes:
      - ./laravel:/app
    command: ["php", "artisan", "queue:work", "--queue=default"]
    depends_on:
      - composer
      - redis
    restart: on-failure

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: ["install"]
    depends_on:
      - pgsql

  pgsql:
    image: postgres:alpine
    container_name: pgsql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./infra/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./infra/data/redis:/data
